nodeLinker: node-modules
nmHoistingLimits: dependencies
yarnPath: .yarn/releases/yarn-2.3.3.cjs
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
